### ISSUE TITLE
Can't load css: sweetalert2.min.css

### ISSUE THREAD

**Issue by vuralanli** [p-v/WeSiSho#1]
When trying to load this extension into chrome I get the following error:
"Can't load css/sweetalert2.min.css" in manifest.json.
 
So I looked what is in the css folder and I only have a "wesisho.global.css" file. Am I doing something wrong or is the "sweetalert2.min.css" file missing?

**Comment by p-v** [comment]
You need to build the plugin first. Just run `npm run dev`  or `npm run debug` for debugging. It will generate files inside the `build` folder.
